# Generated by Django 5.1.3 on 2025-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price, if applicable.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_time',
            field=models.DateTimeField(blank=True, help_text='Flash sale expiration time.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale',
            field=models.BooleanField(default=False, help_text='Is this product in a flash sale?'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_offer',
            field=models.BooleanField(default=False, help_text='Is this product on offer?'),
        ),
    ]
