# Generated by Django 5.1.3 on 2025-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount_price_product_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, help_text='When the discount ends.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, help_text='When the discount starts.', null=True),
        ),
    ]
