# Generated by Django 5.1.3 on 2025-03-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_discount_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_start_date',
        ),
    ]
