# Generated by Django 5.1.3 on 2026-07-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_tenant_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
