# Generated by Django 5.1.3 on 2025-03-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_product'),
        ('products', '0011_remove_product_discount_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_now_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
