# Generated by Django 5.1.3 on 2025-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Unknown Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='closest_town',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='First Name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0700000000', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='town_city',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
