# Generated by Django 5.1.3 on 2025-03-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_address_order_apartment_order_closest_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
