# Generated by Django 5.1.3 on 2025-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
