# Generated by Django 5.1.3 on 2025-10-02 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_from_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_redeemed',
            field=models.IntegerField(default=0),
        ),
    ]
