# Generated by Django 5.1.3 on 2025-10-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_discount_from_points_order_points_earned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_from_points',
        ),
        migrations.RemoveField(
            model_name='order',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='order',
            name='points_redeemed',
        ),
    ]
