# Generated by Django 5.1.3 on 2025-10-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_discount_from_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_cart_item_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
