# Generated by Django 5.1.3 on 2025-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_paid_cart_item_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Payment Initiated', 'Payment Initiated'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
