# Generated by Django 5.1.3 on 2025-10-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_mpesa_checkout_id_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mpesa_checkout_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_cart_item_ids',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
