# Generated by Django 5.1.3 on 2025-10-08 13:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_mpesa_checkout_id_order_paid_cart_item_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mpesa_checkout_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_cart_item_ids',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_from_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_redeemed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
