# Generated by Django 5.1.3 on 2025-10-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_mpesa_checkout_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_from_points',
        ),
        migrations.RemoveField(
            model_name='order',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='order',
            name='points_redeemed',
        ),
    ]
