# Generated by Django 5.1.3 on 2026-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_discount_from_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
