# Generated by Django 5.1.3 on 2026-09-28 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_discount_amount_order_subtotal_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64),
        ),
    ]
