# Generated by Django 5.1.3 on 2026-09-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_tracking_token'),
    ]

    operations = [
    ]
