# Generated by Django 5.1.3 on 2026-09-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_populate_tracking_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_token',
        ),
    ]
