# Generated by Django 5.1.3 on 2025-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('promotion_type', models.CharField(choices=[('banner', 'Banner'), ('popup', 'Pop-up')], default='banner', max_length=10)),
                ('location', models.CharField(blank=True, help_text='e.g., homepage, category_page, product_detail', max_length=50, null=True)),
                ('frequency', models.IntegerField(default=1, help_text='For pop-ups, how often to show')),
            ],
        ),
    ]
