# Generated by Django 5.1.3 on 2025-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
