# Generated by Django 5.1.3 on 2025-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='loyalty_points',
        ),
    ]
